from aiogram.types import ReplyKeyboardMarkup, KeyboardButton


b1 = KeyboardButton('Баланс')
b2 = KeyboardButton('Монеты')
b3 = KeyboardButton('Торговля')
b4 = KeyboardButton('Курс BTC')
b5 = KeyboardButton('Курс ETH')
b6 = KeyboardButton('Купить BTC')
b7 = KeyboardButton('Купить ETH')
b8 = KeyboardButton('Продать BTC')
b9 = KeyboardButton('Продать ETH')
b10 = KeyboardButton('Назад')
b11 = KeyboardButton('Отмена')
b12 = KeyboardButton('Настройки')
b13 = KeyboardButton('Сбросить баланс')
b14 = KeyboardButton('Удалить данные')
b15 = KeyboardButton('/start')
b16 = KeyboardButton('Да')
b17 = KeyboardButton('Нет')

kb_main = ReplyKeyboardMarkup(resize_keyboard=True)
kb_trade = ReplyKeyboardMarkup(resize_keyboard=True)
kb_cancel = ReplyKeyboardMarkup(resize_keyboard=True)
kb_settings = ReplyKeyboardMarkup(resize_keyboard=True)
kb_start = ReplyKeyboardMarkup(resize_keyboard=True)
kb_yes_no = ReplyKeyboardMarkup(resize_keyboard=True)

kb_main.row(b1, b2).row(b3).row(b12)
kb_trade.row(b4, b5).row(b6, b7).row(b8, b9).row(b10)
kb_cancel.row(b11)
kb_settings.insert(b13).insert(b14).row(b10)
kb_start.insert(b15)
kb_yes_no.row(b16, b17)